/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env=preview --include-runtime=false` (hash: 02e6eaf9cadb2c6a448db867da099f98)
interface __BaseEnv_Env {
	APP_ENV: "preview";
	DATABASE_URL: string;
	IP_HASH_SALT: string;
	BETTER_AUTH_SECRET: string;
	BETTER_AUTH_URL: string;
	GOOGLE_CLIENT_ID: string;
	GOOGLE_CLIENT_SECRET: string;
	PUBLIC_GOOGLE_AUTH_ENABLED: string;
	THESTATSAPI_API_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_ENV" | "DATABASE_URL" | "IP_HASH_SALT" | "BETTER_AUTH_SECRET" | "BETTER_AUTH_URL" | "GOOGLE_CLIENT_ID" | "GOOGLE_CLIENT_SECRET" | "PUBLIC_GOOGLE_AUTH_ENABLED" | "THESTATSAPI_API_KEY">> {}
}
