/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env=preview --include-runtime=false` (hash: 4292e9c17839af3c6dda6a7f00eef6c9)
interface __BaseEnv_Env {
	SESSION: KVNamespace;
	APP_ENV: "preview";
	LIVE_MOMENTS_ENABLED: "true";
	DATABASE_URL: string;
	IP_HASH_SALT: string;
	BETTER_AUTH_SECRET: string;
	BETTER_AUTH_URL: string;
	GOOGLE_CLIENT_ID: string;
	GOOGLE_CLIENT_SECRET: string;
	PUBLIC_GOOGLE_AUTH_ENABLED: string;
	THESTATSAPI_API_KEY: string;
	LIVE_MATCH_COORDINATOR: DurableObjectNamespace<import("./src/worker").LiveMatchCoordinator>;
	STATS_API_REQUEST_BROKER: DurableObjectNamespace<import("./src/worker").StatsApiRequestBroker>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
		durableNamespaces: "LiveMatchCoordinator" | "StatsApiRequestBroker";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_ENV" | "LIVE_MOMENTS_ENABLED" | "DATABASE_URL" | "IP_HASH_SALT" | "BETTER_AUTH_SECRET" | "BETTER_AUTH_URL" | "GOOGLE_CLIENT_ID" | "GOOGLE_CLIENT_SECRET" | "PUBLIC_GOOGLE_AUTH_ENABLED" | "THESTATSAPI_API_KEY">> {}
}
